title: ChloroBlog
description: 能鸽善鹉者的领域
email: myosotis@mail.ustc.edu.cn
copyright: Chlorie
baseurl: "/ChloroBlog" # the subpath of your site, e.g. /blog
url: "https://chlorie.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Hydrochlorie
github_username: Chlorie

future:      false  # publish future dated posts --  true, false (default)
highlighter: rouge
markdown:    kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed

sass:
  sass_dir: _sass
  style: compressed

permalink: /:categories/:year-:month-:day/:title.html

# Amount of post to show on home page
paginate: 5

#kramdown:
#  input: GFM
#  auto_ids: true
#  footnote_nr: 1
#  entity_output: as_char
#  toc_levels: 1..6
#  enable_coderay: false

include:
  - .htaccess

exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
